## Contents

01. Aggregating Data Using the groupby and agg function
02. Aggregating Data with transform() 
03. Deriving Columns with loc()

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
path = r'/Users/lindazhang/Instacart Basket Analysis'
ords_prods_derived = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged.pkl'))

In [3]:
df = ords_prods_derived [:1000000]

In [4]:
ords_prods_derived.head()

,order_id,customer_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,order_added_to_cart,reordered,product_name,aisle_id,department_id,prices,price_range,busiest_day,busiest_days,period_of_day,busiest_periods
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6am-11am,Average orders
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,12pm-5pm,Most orders
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,6am-11am,Average orders
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,12pm-5pm,Most orders

## 01. Aggregating Data Using the groupby  and agg function

Always use the groupby() function as part of a series of steps, namely, the following:

1. Split the data into groups based on some criteria.
2. Apply a function to each group separately.
3. Combine the results into a dataframe or alternative data structure or create a new column in the current dataframe.

In [5]:
#Step 1: Split the data into groups based on some criteria. 

df.groupby('product_name')

In [6]:
#Step 2: Apply aggregate function to each group seperately.

### Aggregating Data with agg()

Calculate the mean of the “ordernumber” column grouped by the “department_id” column to compare the average number of orders across each Instacart department.

In [7]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

There are some aggregations that can be conducted without use of the agg() function. For instance, the command above could be replaced with the command below that uses the mean() function to achieve the same results:

In [8]:
df.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [9]:
# Performing Multiple Aggregations

df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

## 02. Aggregating Data with transform()

Create a flag for customers with many orders.

If the maximum orders the user has made is over 40, then the customer will be labeled a “Loyal customer.” If the maximum orders the user has made is over 10 but less than or equal to 40, then the customer will be labeled a “Regular customer.” If the maximum orders the user has made is less than or equal to 10, then the customer will be labeled a “New customer.”

Steps:

1. Split the data into groups based on the “customer_id” column.
2. Apply the transform() function on the “order_number” column to generate the maximum orders for each user.
3. Create a new column, “max_order,” into which you’ll place the results of your aggregation.

In [10]:

ords_prods_derived['max_order'] = ords_prods_derived.groupby(['customer_id'])['order_number'].transform(np.max)

1. A new column called “max_order” is created, which will be what stores the maximum order number for each customer (step 3). 

2. Then, the ords_prods_derived dataframe is grouped by the “customer_id” column (step 1). 

3. And finally, the transform() function is applied on the “order_number” column with the np.max argument (step 2).

np is the NumPy library. The max() function is a function included within NumPy that finds the max value within a column. Including this as an argument within the transform() function tells Python to “transform the ‘order_number’ column by applying the max() function from the NumPy library.”

In [11]:
ords_prods_derived.head(20)

,order_id,customer_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,order_added_to_cart,reordered,product_name,aisle_id,department_id,prices,price_range,busiest_day,busiest_days,period_of_day,busiest_periods,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6am-11am,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,12pm-5pm,Most orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,6am-11am,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,12pm-5pm,Most orders,10
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,10
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,10
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,12pm-5pm,Most orders,10
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,12pm-5pm,Most orders,10
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,6am-11am,Average orders,10
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,22
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,22
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,22
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,22
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,22
15,2293453,19,2,5,14,6.0,196,3,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,9
16,1973799,19,5,6,12,8.0,196,15,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,9
17,532817,19,7,4,17,6.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,12pm-5pm,Most orders,9
18,1573906,21,10,3,10,6.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6am-11am,Average orders,33
19,1593000,31,10,3,8,7.0,196,17,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6am-11am,Average orders,20

In [12]:
ords_prods_derived.head(100)

,order_id,customer_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,order_added_to_cart,reordered,product_name,aisle_id,department_id,prices,price_range,busiest_day,busiest_days,period_of_day,busiest_periods,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6am-11am,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,12pm-5pm,Most orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,6am-11am,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,12pm-5pm,Most orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3226575,360,1,5,12,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,3
96,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,3
97,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,6am-11am,Average orders,8
98,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6pm-11pm,Average orders,22
99,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6pm-11pm,Average orders,22

In [13]:
# Above it didn't show all 100 rows. Here's how you can actually see 100 rows.

pd.options.display.max_rows = None
ords_prods_derived.head(100)

,order_id,customer_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,order_added_to_cart,reordered,product_name,aisle_id,department_id,prices,price_range,busiest_day,busiest_days,period_of_day,busiest_periods,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6am-11am,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,12pm-5pm,Most orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,6am-11am,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,12pm-5pm,Most orders,10
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,10
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,10
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,12pm-5pm,Most orders,10
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,12pm-5pm,Most orders,10
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,6am-11am,Average orders,10
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,22
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,22
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,22
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,22
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,22
15,2293453,19,2,5,14,6.0,196,3,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,9
16,1973799,19,5,6,12,8.0,196,15,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,9
17,532817,19,7,4,17,6.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,12pm-5pm,Most orders,9
18,1573906,21,10,3,10,6.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6am-11am,Average orders,33
19,1593000,31,10,3,8,7.0,196,17,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6am-11am,Average orders,20
20,2231262,31,17,3,11,8.0,196,14,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6am-11am,Average orders,20
21,2580647,43,6,4,16,4.0,196,9,0,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,12pm-5pm,Most orders,11
22,2187180,43,9,4,12,3.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,12pm-5pm,Most orders,11
23,2497897,52,1,1,9,NaN,196,4,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,27
24,1318871,52,2,1,10,7.0,196,5,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,27
25,1261384,52,3,1,10,7.0,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,27
26,580568,52,5,2,10,8.0,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,27
27,2428073,52,7,2,7,8.0,196,5,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,27
28,342306,52,9,1,11,7.0,196,5,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,27
29,1520353,52,10,2,10,8.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,27
30,2542086,52,11,2,9,7.0,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,27
31,944694,52,12,1,16,6.0,196,7,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,12pm-5pm,Most orders,27
32,1268191,52,15,2,11,8.0,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,27
33,1122089,52,17,2,10,6.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,27
34,1498922,52,18,2,10,14.0,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,27
35,180919,52,19,3,8,8.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6am-11am,Average orders,27
36,2695875,52,21,5,10,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,27
37,3205960,67,1,3,11,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6am-11am,Average orders,24
38,970922,67,2,1,15,5.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,12pm-5pm,Most orders,24
39,596585,67,3,1,13,7.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,12pm-5pm,Most orders,24
40,2037087,67,4,2,9,8.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,24
41,2474111,67,5,3,14,8.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,12pm-5pm,Most orders,24
42,1568481,67,6,3,12,7.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,12pm-5pm,Most orders,24
43,2048527,67,8,2,11,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,24
44,2389031,67,9,2,14,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,24
45,2378562,67,10,1,10,6.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,24
46,1515698,67,11,1,11,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,24
47,1928050,67,12,2,12,8.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,24
48,1949274,67,13,1,10,6.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,24
49,551869,67,14,1,9,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,24
50,768572,67,16,4,10,9.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,6am-11am,Average orders,24
51,150528,67,18,5,16,4.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,24
52,29758,67,19,0,14,9.0,196,2,1,Soda,77,7,9.0,Mid-range product,Busiest day,Busiest days,12pm-5pm,Most orders,24
53,1558976,67,21,1,9,5.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,24
54,863974,67,22,1,11,14.0,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,24
55,2308399,67,23,1,14,14.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,12pm-5pm,Most orders,24
56,2759128,81,3,1,9,14.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,7
57,1812985,81,5,2,20,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6pm-11pm,Average orders,7
58,1889835,82,1,3,15,NaN,196,6,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,12pm-5pm,Most orders,19
59,499460,82,3,5,10,5.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,19
60,2728456,82,4,0,11,16.0,196,1,1,Soda,77,7,9.0,Mid-range product,Busiest day,Busiest days,6am-11am,Average orders,19
61,2653743,82,6,4,9,13.0,196,5,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,6am-11am,Average orders,19
62,1358880,82,9,1,10,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,19
63,343588,82,10,2,11,1.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,19
64,3034663,82,15,2,11,12.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,19
65,147262,82,18,1,13,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,12pm-5pm,Most orders,19
66,3144004,82,19,2,15,8.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,19
67,2126069,98,3,0,9,25.0,196,7,0,Soda,77,7,9.0,Mid-range product,Busiest day,Busiest days,6am-11am,Average orders,14
68,2210120,98,7,5,14,5.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,14
69,681011,98,9,3,9,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6am-11am,Average orders,14
70,2846344,98,11,4,13,15.0,196,2,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,12pm-5pm,Most orders,14
71,747431,98,12,6,13,30.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,14
72,2383054,98,13,4,11,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,6am-11am,Average orders,14
73,1993729,98,14,5,8,8.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,14
74,1403849,109,3,3,17,9.0,196,5,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,12pm-5pm,Most orders,6
75,520620,120,1,3,11,NaN,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6am-11am,Average orders,3
76,3273029,120,3,2,8,19.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,3
77,1861943,185,2,1,12,25.0,196,10,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,12pm-5pm,Most orders,6
78,2040988,195,1,1,14,NaN,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,12pm-5pm,Most orders,58
79,1680569,195,8,1,9,4.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6am-11am,Average orders,58
80,276171,195,19,5,11,3.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,58
81,2744976,195,22,5,10,7.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,58
82,2781919,195,25,1,14,4.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,12pm-5pm,Most orders,58
83,1738718,195,31,2,8,4.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,58
84,3058369,195,34,3,10,6.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6am-11am,Average orders,58
85,1485596,195,37,2,15,0.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,58
86,417035,195,40,3,16,2.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,12pm-5pm,Most orders,58
87,1615297,195,47,5,10,2.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,58
88,1765587,195,52,3,12,2.0,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,12pm-5pm,Most orders,58
89,745908,195,57,4,11,3.0,196,3,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,6am-11am,Average orders,58
90,2505656,222,17,2,12,1.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,70
91,3268370,222,38,5,15,1.0,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,70
92,2016711,290,9,5,19,6.0,196,8,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6pm-11pm,Average orders,51
93,2706088,290,28,6,10,7.0,196,16,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,6am-11am,Average orders,51
94,1952286,331,6,5,16,30.0,196,8,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,8
95,3226575,360,1,5,12,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,3
96,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,12pm-5pm,Most orders,3
97,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,6am-11am,Average orders,8
98,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,6pm-11pm,Average orders,22
99,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,6pm-11pm,Average orders,22

## 03. Deriving Columns with loc()

In [14]:
# Create a flag that assigns a “loyalty” label to a user ID based on its corresponding max order value.

ords_prods_derived.loc[ords_prods_derived['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
ords_prods_derived.loc[(ords_prods_derived['max_order'] <= 40) & (ords_prods_derived['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
ords_prods_derived.loc[ords_prods_derived['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [15]:
ords_prods_derived['loyalty_flag'].value_counts(dropna = False)

Regular customer    15890458
Loyal customer      10293434
New customer         6249138
Name: loyalty_flag, dtype: int64

In [16]:
# Here's how you can check specific columns using the head() function:

ords_prods_derived[['customer_id','max_order', 'loyalty_flag', 'order_number']].head(60)

    customer_id  max_order      loyalty_flag  order_number
0             1         10      New customer             1
1             1         10      New customer             2
2             1         10      New customer             3
3             1         10      New customer             4
4             1         10      New customer             5
5             1         10      New customer             6
6             1         10      New customer             7
7             1         10      New customer             8
8             1         10      New customer             9
9             1         10      New customer            10
10           15         22  Regular customer            15
11           15         22  Regular customer            17
12           15         22  Regular customer            18
13           15         22  Regular customer            21
14           15         22  Regular customer            22
15           19          9      New customer             2
16           19          9      New customer             5
17           19          9      New customer             7
18           21         33  Regular customer            10
19           31         20  Regular customer            10
20           31         20  Regular customer            17
21           43         11  Regular customer             6
22           43         11  Regular customer             9
23           52         27  Regular customer             1
24           52         27  Regular customer             2
25           52         27  Regular customer             3
26           52         27  Regular customer             5
27           52         27  Regular customer             7
28           52         27  Regular customer             9
29           52         27  Regular customer            10
30           52         27  Regular customer            11
31           52         27  Regular customer            12
32           52         27  Regular customer            15
33           52         27  Regular customer            17
34           52         27  Regular customer            18
35           52         27  Regular customer            19
36           52         27  Regular customer            21
37           67         24  Regular customer             1
38           67         24  Regular customer             2
39           67         24  Regular customer             3
40           67         24  Regular customer             4
41           67         24  Regular customer             5
42           67         24  Regular customer             6
43           67         24  Regular customer             8
44           67         24  Regular customer             9
45           67         24  Regular customer            10
46           67         24  Regular customer            11
47           67         24  Regular customer            12
48           67         24  Regular customer            13
49           67         24  Regular customer            14
50           67         24  Regular customer            16
51           67         24  Regular customer            18
52           67         24  Regular customer            19
53           67         24  Regular customer            21
54           67         24  Regular customer            22
55           67         24  Regular customer            23
56           81          7      New customer             3
57           81          7      New customer             5
58           82         19  Regular customer             1
59           82         19  Regular customer             3

## Task 4.8

In [17]:
#2. Find the aggregated mean of the “order_number” column grouped by “department_id” for a subset of your dataframe.

ords_prods_derived.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457687
2                17.277920
3                17.179756
4                17.811403
5                15.215751
6                16.439806
7                17.225773
8                15.340520
9                15.895474
10               20.197148
11               16.170371
12               15.887622
13               16.583304
14               16.759763
15               16.165037
16               17.663250
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

#3. It looks like the average number of orders across departments for the whole ords_prods_derived is similar to the subset.

#5 Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer). What you’re trying to determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers.

In [18]:
# find the min, max, and mean of prices for different loyalty customer groups 

ords_prods_derived.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.388854  1.0  99999.0
New customer      13.294634  1.0  99999.0
Regular customer  12.496419  1.0  99999.0

Looks like loyal customers (customers with more than 40 orders) buy the least expensive products.

#6.The team now wants to target different types of spenders in their marketing campaigns. This can be achieved by looking at the prices of the items people are buying. Create a spending flag for each user based on the average price across all their orders using the following criteria:

If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”

If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

In [19]:
# Split the data into groups based on the “customer_id” column.
# Apply the transform() function on the “prices” column to generate the mean price spent for each user.
# Create a new column, 'mean_spend' into which you’ll place the results of your aggregation.


ords_prods_derived['mean_spend'] = ords_prods_derived.groupby(['customer_id'])['prices'].transform(np.mean)

In [20]:
# Create a flag that assigns a spend label to customer_id based on its corresponding mean_spend value.

ords_prods_derived.loc[ords_prods_derived['mean_spend'] < 10, 'spend_flag'] = 'Low spender'
ords_prods_derived.loc[ords_prods_derived['mean_spend'] >= 10, 'spend_flag'] = 'High spender'

In [21]:
ords_prods_derived[['customer_id', 'mean_spend', 'spend_flag']].head(60)

    customer_id  mean_spend   spend_flag
0             1    6.367797  Low spender
1             1    6.367797  Low spender
2             1    6.367797  Low spender
3             1    6.367797  Low spender
4             1    6.367797  Low spender
5             1    6.367797  Low spender
6             1    6.367797  Low spender
7             1    6.367797  Low spender
8             1    6.367797  Low spender
9             1    6.367797  Low spender
10           15    3.980556  Low spender
11           15    3.980556  Low spender
12           15    3.980556  Low spender
13           15    3.980556  Low spender
14           15    3.980556  Low spender
15           19    8.372059  Low spender
16           19    8.372059  Low spender
17           19    8.372059  Low spender
18           21    7.012683  Low spender
19           31    8.137793  Low spender
20           31    8.137793  Low spender
21           43    7.444898  Low spender
22           43    7.444898  Low spender
23           52    6.408876  Low spender
24           52    6.408876  Low spender
25           52    6.408876  Low spender
26           52    6.408876  Low spender
27           52    6.408876  Low spender
28           52    6.408876  Low spender
29           52    6.408876  Low spender
30           52    6.408876  Low spender
31           52    6.408876  Low spender
32           52    6.408876  Low spender
33           52    6.408876  Low spender
34           52    6.408876  Low spender
35           52    6.408876  Low spender
36           52    6.408876  Low spender
37           67    7.656790  Low spender
38           67    7.656790  Low spender
39           67    7.656790  Low spender
40           67    7.656790  Low spender
41           67    7.656790  Low spender
42           67    7.656790  Low spender
43           67    7.656790  Low spender
44           67    7.656790  Low spender
45           67    7.656790  Low spender
46           67    7.656790  Low spender
47           67    7.656790  Low spender
48           67    7.656790  Low spender
49           67    7.656790  Low spender
50           67    7.656790  Low spender
51           67    7.656790  Low spender
52           67    7.656790  Low spender
53           67    7.656790  Low spender
54           67    7.656790  Low spender
55           67    7.656790  Low spender
56           81    8.262963  Low spender
57           81    8.262963  Low spender
58           82    6.441221  Low spender
59           82    6.441221  Low spender

#7.In order to send relevant notifications to users within the app (for instance, asking users if they want to buy the same item again), the Instacart team wants you to determine frequent versus non-frequent customers. Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. The criteria for the flag should be as follows:

If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”

If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”

If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”

In [22]:
# Split the data into groups based on the “customer_id” column.
# Apply the transform() function on the “days_since_prior_order” column to generate the median number of days since last order for each user.
# Create a new column, 'median_days_since_prior_order' into which you’ll place the results of your aggregation.

ords_prods_derived['median_days_since_prior_order'] = ords_prods_derived.groupby(['customer_id'])['days_since_prior_order'].transform(np.median)

In [23]:
# Create a flag that assigns a customer frequency label to customer_id based on its corresponding median_days_since_prior_order.

ords_prods_derived.loc[ords_prods_derived['median_days_since_prior_order'] > 20, 'customer_frequency'] = 'Non-frequent customer'
ords_prods_derived.loc[(ords_prods_derived['median_days_since_prior_order'] > 10) & (ords_prods_derived['median_days_since_prior_order'] <= 20), 'customer_frequency'] = 'Regular customer'
ords_prods_derived.loc[ords_prods_derived['median_days_since_prior_order'] <= 10, 'customer_frequency'] = 'Frequent customer'

In [24]:
ords_prods_derived[['customer_id', 'median_days_since_prior_order', 'customer_frequency']].head(60)

    customer_id  median_days_since_prior_order     customer_frequency
0             1                           20.5  Non-frequent customer
1             1                           20.5  Non-frequent customer
2             1                           20.5  Non-frequent customer
3             1                           20.5  Non-frequent customer
4             1                           20.5  Non-frequent customer
5             1                           20.5  Non-frequent customer
6             1                           20.5  Non-frequent customer
7             1                           20.5  Non-frequent customer
8             1                           20.5  Non-frequent customer
9             1                           20.5  Non-frequent customer
10           15                           10.0      Frequent customer
11           15                           10.0      Frequent customer
12           15                           10.0      Frequent customer
13           15                           10.0      Frequent customer
14           15                           10.0      Frequent customer
15           19                            6.0      Frequent customer
16           19                            6.0      Frequent customer
17           19                            6.0      Frequent customer
18           21                            7.5      Frequent customer
19           31                            6.0      Frequent customer
20           31                            6.0      Frequent customer
21           43                           10.0      Frequent customer
22           43                           10.0      Frequent customer
23           52                            8.0      Frequent customer
24           52                            8.0      Frequent customer
25           52                            8.0      Frequent customer
26           52                            8.0      Frequent customer
27           52                            8.0      Frequent customer
28           52                            8.0      Frequent customer
29           52                            8.0      Frequent customer
30           52                            8.0      Frequent customer
31           52                            8.0      Frequent customer
32           52                            8.0      Frequent customer
33           52                            8.0      Frequent customer
34           52                            8.0      Frequent customer
35           52                            8.0      Frequent customer
36           52                            8.0      Frequent customer
37           67                            7.0      Frequent customer
38           67                            7.0      Frequent customer
39           67                            7.0      Frequent customer
40           67                            7.0      Frequent customer
41           67                            7.0      Frequent customer
42           67                            7.0      Frequent customer
43           67                            7.0      Frequent customer
44           67                            7.0      Frequent customer
45           67                            7.0      Frequent customer
46           67                            7.0      Frequent customer
47           67                            7.0      Frequent customer
48           67                            7.0      Frequent customer
49           67                            7.0      Frequent customer
50           67                            7.0      Frequent customer
51           67                            7.0      Frequent customer
52           67                            7.0      Frequent customer
53           67                            7.0      Frequent customer
54           67                            7.0      Frequent customer
55           67                            7.0      Frequent customer
56           81                           30.0  Non-frequent customer
57           81                           30.0  Non-frequent customer
58           82                           11.5       Regular customer
59           82                           11.5       Regular customer

In [25]:
ords_prods_derived.head()

,order_id,customer_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,order_added_to_cart,reordered,product_name,...,busiest_day,busiest_days,period_of_day,busiest_periods,max_order,loyalty_flag,mean_spend,spend_flag,median_days_since_prior_order,customer_frequency
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,Regularly busy,Regularly busy,6am-11am,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,Regularly busy,Slowest days,6am-11am,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,Regularly busy,Slowest days,12pm-5pm,Most orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,Least busy,Slowest days,6am-11am,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,Least busy,Slowest days,12pm-5pm,Most orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer

In [26]:
ords_prods_derived.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_merged.pkl'))